import { Theme, createStyles, makeStyles } from '@material-ui/core';

export const SignUpStyles = makeStyles(
  (theme: Theme) =>
    createStyles({
      getStartedContainer: {
        textAlign: 'center',
        marginBottom: 70,
      },
      title: {
        fontSize: 40,
        fontWeight: 700,
        color: '#0B1F35',
        textAlign: 'center',
        padding: 10,
      },
      subTitle: {
        fontSize: 16,
        fontWeight: 400,
        color: '#6D7986',
        width: 804,
        margin: 'auto',
        textAlign: 'center',
        padding: 10,
      },
      startFlexContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        width: '100vw',
      },
      dividerLine: {
        flexGrow: 1,
        backgroundColor: '#6D7986',
        height: 1,
        display: 'inline-block',
        opacity: 0.4,
      },
      dividerText: {
        color: '#6D7986',
        flexGrow: 0,
        opacity: 0.4,
      },
      buttonContainer: {
        padding: 25,
      },
      connectButton: {
        width: 450,
        height: 60,
        cursor: 'pointer',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        border: '1px solid rgba(109, 121, 134, 0.3)',
        borderRadius: 6,
        boxSizing: 'border-box',
        margin: 'auto',
      },
      logoImage: {
        margin: 'auto',
        marginLeft: -10,
      },
      connectButtonText: {
        fontWeight: 700,
        fontSize: 14,
        margin: 'auto',
        color: '#0B1F35',
      },
      arrow: {
        margin: 'auto',
      },
      tryDemoTitle: {
        fontSize: 34,
        fontWeight: 700,
        padding: 15,
      },
      tryDemoSubtitle: {
        fontWeight: 400,
        fontSize: 20,
        padding: 15,
        width: 405,
        marginBottom: 30,
      },
      tryDemoButton: {
        fontSize: 12,
        fontWeight: 700,
        border: '1px solid #FFFFFF',
        width: 198,
        height: 60,
        paddingTop: 20,
        paddingLeft: 50,
        borderRadius: 6,
        cursor: 'pointer',
        marginLeft: 10,
      },
      whiteArrow: {
        marginLeft: 10,
      },
      edgeBoxContainer: {
        display: 'flex',
        justifyContent: 'center',
        flexWrap: 'wrap',
      },
      edgeContainer: {
        backgroundColor: '#FBFCFE',
        border: '1px solid #CBD2DC',
        boxSizing: 'border-box',
        borderRadius: 6,
        width: 364,
        height: 239,
        display: 'inline-block',
        margin: 15,
        padding: 20,
      },
      edgeBoxImage: {
        width: 45,
        height: 40,
      },
      edgeBoxTitle: {
        fontSize: 22,
        fontWeight: 700,
        marginLeft: 20,
        color: '#05143A',
        display: 'inline-block',
      },
      edgeBoxContent: {
        paddingTop: 30,
        color: '#848DA3',
        fontSize: 14,
        fontWeight: 400,
      },
      edgeConnectButton: {
        border: '1px solid #CBD2DC',
        backgroundColor: '#FFFFFF',
        width: 142,
        height: 40,
        color: '#05143A',
        fontSize: 12,
        fontWeight: 700,
        cursor: 'pointer',
        borderRadius: 6,
        paddingTop: 10,
        paddingLeft: 30,
        marginTop: 20,
        marginLeft: 170,
      },
      newEdgeButton: {
        border: '1px dashed #CBD2DC',
        boxSizing: 'border-box',
        borderRadius: 6,
        width: 364,
        height: 239,
        display: 'inline-block',
        margin: 15,
        paddingTop: 110,
        paddingLeft: 120,
        fontSize: 12,
        fontWeight: 700,
        cursor: 'pointer',
      },
      flexContainer: {
        display: 'flex',
        justifyContent: 'space-between',
        paddingRight: 15,
        paddingLeft: 15,
        marginTop: 30,
      },
      startButton: {
        height: 60,
        width: 198,
        fontSize: 12,
        fontWeight: 700,
        borderRadius: 6,
        cursor: 'pointer',
      },
      skipSetupButton: {
        height: 60,
        width: 198,
        fontSize: 12,
        fontWeight: 700,
        border: '1px solid #CBD2DC',
        borderRadius: 6,
        paddingTop: 20,
        paddingLeft: 50,
        cursor: 'pointer',
      },
      skipSetupText: {
        color: '#848DA3',
        fontWeight: 400,
        fontSize: 14,
        textAlign: 'center',
        padding: 10,
      },
      topBar: {
        backgroundColor: '#F3F6FC',
        height: '80px',
        width: '70%',
        padding: 25,
        paddingRight: 40,
        position: 'fixed',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      topBarText: {
        fontSize: 18,
        fontWeight: 700,
        color: '#05143A',
        paddingRight: 20,
      },
      topBarflexContainer: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
      },
    }),
  {
    index: 1,
  },
);
