import { ISelectedListItem } from 'lib/models/general';
import { IElasticField } from 'lib/api/ApiModels/paramBuilders';

export enum IQuryFieldtype {
  STRING = 'string',
  NUMBER = 'number',
}
export interface ISessionsGridField {
  id?: string;
  resField: string;
  searchField: string;
  queryType?: IQuryFieldtype;
  label: string;
  isStaticField?: boolean;
  isCustomField?: boolean;
}

export interface ISessionsGridFieldColumn extends ISessionsGridField {
  hide: boolean;
}

export interface ISessionGridColumns {
  [key: string]: ISessionsGridField;
}

export const SessionGridColumns: ISessionGridColumns = {
  collapseColumn: {
    id: 'aggregatedId',
    resField: 'id',
    searchField: '',
    queryType: null,
    label: '',
    isStaticField: true,
    isCustomField: true,
  },
  vendorsColumn: {
    id: 'aggregatedVendors',
    resField: 'vendors',
    searchField: '',
    queryType: null,
    label: 'Vendor',
    isStaticField: true,
    isCustomField: true,
  },
  timestamp: {
    id: 'aggregatedTimestamp',
    resField: 'timestamp',
    searchField: '@timestamp',
    queryType: IQuryFieldtype.STRING,
    label: 'Time',
    isStaticField: true,
    isCustomField: false,
  },
  startTime: {
    id: 'aggregatedstartTime',
    resField: 'startTime',
    searchField: 'start_time',
    queryType: IQuryFieldtype.STRING,
    label: 'Start Time',
    isStaticField: true,
    isCustomField: false,
  },
  endTime: {
    id: 'aggregatedendTime',
    resField: 'endTime',
    searchField: 'end_time',
    queryType: IQuryFieldtype.STRING,
    label: 'End Time',
    isStaticField: true,
    isCustomField: false,
  },
  sessionId: {
    id: 'aggregatedSessionId',
    resField: 'sessionId',
    searchField: 'sessionid',
    queryType: IQuryFieldtype.STRING,
    label: 'Session ID',
    isStaticField: true,
    isCustomField: false,
  },
  flowId: {
    id: 'aggregatedFlowId',
    resField: 'flowId',
    searchField: 'flowid',
    queryType: IQuryFieldtype.STRING,
    label: 'Flow ID',
    isStaticField: true,
    isCustomField: false,
  },
  flowDirection: {
    id: 'aggregatedflowDirection',
    resField: 'flowDirection',
    searchField: 'flow_direction',
    queryType: IQuryFieldtype.STRING,
    label: 'Flow Direction',
    isStaticField: true,
    isCustomField: false,
  },
  sourceIp: {
    id: 'aggregatedSourceIp',
    resField: 'sourceIp',
    searchField: 'source_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Source IP',
    isStaticField: true,
    isCustomField: false,
  },
  sourcePort: {
    id: 'aggregatedSourcePort',
    resField: 'sourcePort',
    searchField: 'source_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Source Port',
    isStaticField: true,
    isCustomField: false,
  },
  sourceOrgid: {
    id: 'aggregatedsourceOrgid',
    resField: 'sourceOrgid',
    searchField: 'source_orgid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Organization ID',
    isStaticField: true,
    isCustomField: false,
  },
  sourceVnetworkExtid: {
    id: 'aggregatedsourceVnetworkExtid',
    resField: 'sourceVnetworkExtid',
    searchField: 'source_vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Vnetwork Ext ID',
    isStaticField: true,
    isCustomField: false,
  },
  sourceVnetworkName: {
    id: 'aggregatedsourceVnetworkName',
    resField: 'sourceVnetworkName',
    searchField: 'source_vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Vnetwork Name',
    isStaticField: true,
    isCustomField: false,
  },
  sourceSubnetExtid: {
    id: 'aggregatedsourceSubnetExtid',
    resField: 'sourceSubnetExtid',
    searchField: 'source_subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Subnet Ext ID',
    isStaticField: true,
    isCustomField: false,
  },
  sourceVmExtid: {
    id: 'aggregatedsourceVmExtid',
    resField: 'sourceVmExtid',
    searchField: 'source_vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VM Ext ID',
    isStaticField: true,
    isCustomField: false,
  },
  sourceVmName: {
    id: 'aggregatedsourceVmName',
    resField: 'sourceVmName',
    searchField: 'source_vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VM Name',
    isStaticField: true,
    isCustomField: false,
  },
  sourceRegion: {
    id: 'aggregatedsourceRegion',
    resField: 'sourceRegion',
    searchField: 'source_region',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Region',
    isStaticField: true,
    isCustomField: false,
  },
  sourceControllerName: {
    id: 'aggregatedsourceControllerName',
    resField: 'sourceControllerName',
    searchField: 'source_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Controller Name',
    isStaticField: true,
    isCustomField: false,
  },
  sourceControllerId: {
    id: 'aggregatedsourceControllerId',
    resField: 'sourceControllerId',
    searchField: 'source_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Controller ID',
    isStaticField: true,
    isCustomField: false,
  },
  sourceSegmentId: {
    id: 'aggregatedsourceSegmentId',
    resField: 'sourceSegmentId',
    searchField: 'source_segment_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Segment ID',
    isStaticField: true,
    isCustomField: false,
  },
  destIp: {
    id: 'aggregatedDestIp',
    resField: 'destIp',
    searchField: 'dest_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination IP',
    isStaticField: true,
    isCustomField: false,
  },
  destPort: {
    id: 'aggregatedDestPort',
    resField: 'destPort',
    searchField: 'dest_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Destination Port',
    isStaticField: true,
    isCustomField: false,
  },
  destOrgid: {
    id: 'aggregateddestOrgid',
    resField: 'destOrgid',
    searchField: 'dest_orgid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Organization ID',
    isStaticField: true,
    isCustomField: false,
  },
  destVnetworkExtid: {
    id: 'aggregateddestVnetworkExtid',
    resField: 'destVnetworkExtid',
    searchField: 'dest_vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Vnetwork Ext ID',
    isStaticField: true,
    isCustomField: false,
  },
  destVnetworkName: {
    id: 'aggregateddestVnetworkName',
    resField: 'destVnetworkName',
    searchField: 'dest_vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Vnetwork Name',
    isStaticField: true,
    isCustomField: false,
  },
  destSubnetExtid: {
    id: 'aggregateddestSubnetExtid',
    resField: 'destSubnetExtid',
    searchField: 'dest_subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Subnet Ext ID',
    isStaticField: true,
    isCustomField: false,
  },
  destVmExtid: {
    id: 'aggregateddestVmExtid',
    resField: 'destVmExtid',
    searchField: 'dest_vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VM Ext ID',
    isStaticField: true,
    isCustomField: false,
  },
  destVmName: {
    id: 'aggregateddestVmName',
    resField: 'destVmName',
    searchField: 'dest_vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VM Name',
    isStaticField: true,
    isCustomField: false,
  },
  destRegion: {
    id: 'aggregateddestRegion',
    resField: 'destRegion',
    searchField: 'dest_region',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Region',
    isStaticField: true,
    isCustomField: false,
  },
  destControllerName: {
    id: 'aggregateddestControllerName',
    resField: 'destControllerName',
    searchField: 'dest_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Controller Name',
    isStaticField: true,
    isCustomField: false,
  },
  destControllerId: {
    id: 'aggregateddestControllerId',
    resField: 'destControllerId',
    searchField: 'dest_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Controller ID',
    isStaticField: true,
    isCustomField: false,
  },
  destSegmentId: {
    id: 'aggregateddestSegmentId',
    resField: 'destSegmentId',
    searchField: 'dest_segment_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Segment ID',
    isStaticField: true,
    isCustomField: false,
  },
  natSourceIp: {
    id: 'aggregatedNatSourceIp',
    resField: 'natSourceIp',
    searchField: 'nat_source_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Nat Source IP',
    isStaticField: true,
    isCustomField: false,
  },
  natSourcePort: {
    id: 'aggregatedNatSourcePort',
    resField: 'natSourcePort',
    searchField: 'nat_source_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Nat Source Port',
    isStaticField: true,
    isCustomField: false,
  },
  natDestIp: {
    id: 'aggregatedNatDestIp',
    resField: 'natDestIp',
    searchField: 'nat_dest_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Nat Destination IP',
    isStaticField: true,
    isCustomField: false,
  },
  natDestPort: {
    id: 'aggregatedNatDestPort',
    resField: 'natDestPort',
    searchField: 'nat_dest_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Nat Destination Port',
    isStaticField: true,
    isCustomField: false,
  },
  deviceName: {
    id: 'aggregatedDeviceName',
    resField: 'deviceName',
    searchField: 'device_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Name',
    isStaticField: true,
    isCustomField: false,
  },
  deviceExtId: {
    id: 'aggregatedDeviceExtId',
    resField: 'deviceExtId',
    searchField: 'device_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Device ID',
    isStaticField: true,
    isCustomField: false,
  },
  deviceVendor: {
    id: 'aggregatedDeviceVendor',
    resField: 'deviceVendor',
    searchField: 'device_vendor',
    queryType: IQuryFieldtype.STRING,
    label: 'Vendor',
    isStaticField: true,
    isCustomField: false,
  },
  deviceNetworkExtid: {
    id: 'aggregateddeviceNetworkExtid',
    resField: 'deviceNetworkExtid',
    searchField: 'device_network_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Network Ext ID',
    isStaticField: true,
    isCustomField: false,
  },
  deviceControllerId: {
    id: 'aggregateddeviceControllerId',
    resField: 'deviceControllerId',
    searchField: 'device_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Controller ID',
    isStaticField: true,
    isCustomField: false,
  },
  deviceControllerName: {
    id: 'aggregateddeviceControllerName',
    resField: 'deviceControllerName',
    searchField: 'device_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Controller Name',
    isStaticField: true,
    isCustomField: false,
  },
  bytes: {
    id: 'aggregatedDeviceBytes',
    resField: 'bytes',
    searchField: 'bytes',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Bytes',
    isStaticField: true,
    isCustomField: false,
  },
  packets: {
    id: 'aggregatedDevicePackets',
    resField: 'packets',
    searchField: 'packets',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Packets',
    isStaticField: true,
    isCustomField: false,
  },
  action: {
    id: 'aggregatedDeviceAction',
    resField: 'action',
    searchField: 'action',
    queryType: IQuryFieldtype.STRING,
    label: 'Action',
    isStaticField: true,
    isCustomField: false,
  },
  tcpFlags: {
    id: 'aggregatedDeviceTcpFlags',
    resField: 'tcpFlags',
    searchField: 'tcp_flags',
    queryType: IQuryFieldtype.STRING,
    label: 'TCP Flags',
    isStaticField: true,
    isCustomField: false,
  },
  trafficType: {
    id: 'aggregatedDeviceTrafficType',
    resField: 'trafficType',
    searchField: 'traffic_type',
    queryType: IQuryFieldtype.STRING,
    label: 'Traffic Type',
    isStaticField: true,
    isCustomField: false,
  },
  vnetworkExtId: {
    id: 'aggregatedDeviceVnetworkExtId',
    resField: 'vnetworkExtId',
    searchField: 'vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'VPC Id',
    isStaticField: true,
    isCustomField: false,
  },
  vnetworkName: {
    id: 'aggregatedDeviceVnetworkName',
    resField: 'vnetworkName',
    searchField: 'vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'VPC Name',
    isStaticField: true,
    isCustomField: false,
  },
  subnetExtId: {
    id: 'aggregatedDeviceSubnetExtId',
    resField: 'subnetExtId',
    searchField: 'subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Subnet Id',
    isStaticField: true,
    isCustomField: false,
  },
  subnetName: {
    id: 'aggregatedDeviceSubnetName',
    resField: 'subnetName',
    searchField: 'subnet_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Subnet Name',
    isStaticField: true,
    isCustomField: false,
  },
  vmExtId: {
    id: 'aggregatedDeviceVmExtId',
    resField: 'VmExtId',
    searchField: 'vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'VM Id',
    isStaticField: true,
    isCustomField: false,
  },
  vmName: {
    id: 'aggregatedDeviceVmName',
    resField: 'vmName',
    searchField: 'vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'VM Name',
    isStaticField: true,
    isCustomField: false,
  },
  region: {
    id: 'aggregatedDeviceRegion',
    resField: 'region',
    searchField: 'region',
    queryType: IQuryFieldtype.STRING,
    label: 'Region',
    isStaticField: true,
    isCustomField: false,
  },
  azId: {
    id: 'aggregatedDeviceAzId',
    resField: 'azId',
    searchField: 'az_id',
    queryType: IQuryFieldtype.STRING,
    label: 'AZ Id',
    isStaticField: true,
    isCustomField: false,
  },
  protocol: {
    id: 'aggregatedProtocol',
    resField: 'protocol',
    searchField: 'protocol',
    queryType: IQuryFieldtype.STRING,
    label: 'Protocol',
    isStaticField: true,
    isCustomField: false,
  },
  policyAction: {
    id: 'aggregatedpolicyAction',
    resField: 'policyAction',
    searchField: 'policy_action',
    queryType: IQuryFieldtype.STRING,
    label: 'Policy Action',
    isStaticField: true,
    isCustomField: false,
  },
};

export const SessionElasticFieldItems: IElasticField[] = [
  {
    resField: 'timestamp',
    searchField: '@timestamp',
    queryType: IQuryFieldtype.STRING,
    label: 'Time',
    isField: true,
  },
  {
    resField: 'sessionId',
    searchField: 'sessionid',
    queryType: IQuryFieldtype.STRING,
    label: 'Session ID',
    isField: true,
  },
  {
    resField: 'flowId',
    searchField: 'flowid',
    queryType: IQuryFieldtype.STRING,
    label: 'Flow ID',
    isField: true,
  },
  {
    resField: 'sourceIp',
    searchField: 'source_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Source IP',
    isField: true,
  },
  {
    resField: 'sourcePort',
    searchField: 'source_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Source Port',
    isField: true,
  },
  {
    resField: 'destIp',
    searchField: 'dest_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination IP',
    isField: true,
  },
  {
    resField: 'destPort',
    searchField: 'dest_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Destination Port',
    isField: true,
  },
  {
    resField: 'natSourceIp',
    searchField: 'nat_source_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Nat Source IP',
    isField: true,
  },
  {
    resField: 'natSourcePort',
    searchField: 'nat_source_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Nat Source Port',
    isField: true,
  },
  {
    resField: 'natDestIp',
    searchField: 'nat_dest_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Nat Destination IP',
    isField: true,
  },
  {
    resField: 'natDestPort',
    searchField: 'nat_dest_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Nat Destination Port',
    isField: true,
  },
  {
    resField: 'deviceName',
    searchField: 'device_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Name',
    isField: true,
  },
  {
    resField: 'deviceExtId',
    searchField: 'device_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Device ID',
    isField: true,
  },
  {
    resField: 'device',
    searchField: 'device',
    queryType: IQuryFieldtype.STRING,
    label: 'Device',
    isField: true,
  },
  {
    resField: 'deviceVendor',
    searchField: 'device_vendor',
    queryType: IQuryFieldtype.STRING,
    label: 'Vendor',
    isField: true,
  },
  {
    resField: 'bytes',
    searchField: 'bytes',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Bytes',
    isField: true,
  },
  {
    resField: 'packets',
    searchField: 'packets',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Packets',
    isField: true,
  },
  {
    resField: 'action',
    searchField: 'action',
    queryType: IQuryFieldtype.STRING,
    label: 'Action',
    isField: true,
    valueTransform: v => v.toUpperCase(),
  },
  {
    resField: 'tcpFlags',
    searchField: 'tcp_flags',
    queryType: IQuryFieldtype.STRING,
    label: 'TCP Flags',
    isField: true,
  },
  {
    resField: 'trafficType',
    searchField: 'traffic_type',
    queryType: IQuryFieldtype.STRING,
    label: 'Traffic Type',
    isField: true,
  },
  {
    resField: 'vnetworkExtId',
    searchField: 'vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'VPC Id',
    isField: true,
  },
  {
    resField: 'vnetworkName',
    searchField: 'vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'VPC Name',
    isField: true,
  },
  {
    resField: 'subnetExtId',
    searchField: 'subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Subnet Id',
    isField: true,
  },

  {
    resField: 'VmExtId',
    searchField: 'vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'VM Id',
    isField: true,
  },
  {
    resField: 'vmName',
    searchField: 'vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'VM Name',
    isField: true,
  },
  {
    resField: 'region',
    searchField: 'region',
    queryType: IQuryFieldtype.STRING,
    label: 'Region',
    isField: true,
  },
  {
    resField: 'azId',
    searchField: 'az_id',
    queryType: IQuryFieldtype.STRING,
    label: 'AZ Id',
    isField: true,
  },
  {
    resField: 'protocol',
    searchField: 'protocol',
    queryType: IQuryFieldtype.STRING,
    label: 'Protocol',
    isField: true,
  },
  {
    resField: 'policyAction',
    searchField: 'policy_action',
    queryType: IQuryFieldtype.STRING,
    label: 'Policy Action',
    isField: true,
  },
  {
    resField: 'flowDirection',
    searchField: 'flow_direction',
    queryType: IQuryFieldtype.STRING,
    label: 'Flow Direction',
    isField: true,
  },
  {
    resField: 'startTime',
    searchField: 'start_time',
    queryType: IQuryFieldtype.STRING,
    label: 'Start Time',
    isField: true,
  },
  {
    resField: 'endTime',
    searchField: 'end_time',
    queryType: IQuryFieldtype.STRING,
    label: 'End Time',
    isField: true,
  },
  {
    resField: 'deviceNetworkExtid',
    searchField: 'device_network_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Network Ext ID',
    isField: true,
  },
  {
    resField: 'deviceControllerId',
    searchField: 'device_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Controller ID',
    isField: true,
  },
  {
    resField: 'deviceControllerName',
    searchField: 'device_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Controller Name',
    isField: true,
  },
  {
    resField: 'sourceOrgid',
    searchField: 'source_orgid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Organization ID',
    isField: true,
  },
  {
    resField: 'sourceVnetworkExtid',
    searchField: 'source_vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Vnetwork Ext ID',
    isField: true,
  },
  {
    resField: 'sourceVnetworkName',
    searchField: 'source_vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Vnetwork Name',
    isField: true,
  },
  {
    resField: 'sourceSubnetExtid',
    searchField: 'source_subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Subnet Ext ID',
    isField: true,
  },
  {
    resField: 'sourceVmExtid',
    searchField: 'source_vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VM Ext ID',
    isField: true,
  },
  {
    resField: 'sourceVmName',
    searchField: 'source_vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VM Name',
    isField: true,
  },
  {
    resField: 'sourceRegion',
    searchField: 'source_region',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Region',
    isField: true,
  },
  {
    resField: 'sourceControllerName',
    searchField: 'source_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Controller Name',
    isField: true,
  },
  {
    resField: 'sourceControllerId',
    searchField: 'source_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Controller ID',
    isField: true,
  },
  {
    resField: 'sourceSegmentId',
    searchField: 'source_segment_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Segment ID',
    isField: true,
  },
  {
    resField: 'destOrgid',
    searchField: 'dest_orgid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Organization ID',
    isField: true,
  },
  {
    resField: 'destVnetworkExtid',
    searchField: 'dest_vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Vnetwork Ext ID',
    isField: true,
  },
  {
    resField: 'destVnetworkName',
    searchField: 'dest_vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Vnetwork Name',
    isField: true,
  },
  {
    resField: 'destSubnetExtid',
    searchField: 'dest_subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Subnet Ext ID',
    isField: true,
  },
  {
    resField: 'destVmExtid',
    searchField: 'dest_vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VM Ext ID',
    isField: true,
  },
  {
    resField: 'destVmName',
    searchField: 'dest_vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VM Name',
    isField: true,
  },
  {
    resField: 'destRegion',
    searchField: 'dest_region',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Region',
    isField: true,
  },
  {
    resField: 'destControllerName',
    searchField: 'dest_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Controller Name',
    isField: true,
  },
  {
    resField: 'destControllerId',
    searchField: 'dest_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Controller ID',
    isField: true,
  },
  {
    resField: 'destSegmentId',
    searchField: 'dest_segment_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Segment ID',
    isField: true,
  },
];

export enum FilterOpperatorTypes {
  AND = 'AND',
  OR = 'OR',
}

export const FilterOpperatorsList: ISelectedListItem<FilterOpperatorTypes>[] = [
  {
    id: FilterOpperatorTypes.AND,
    label: 'And',
    value: FilterOpperatorTypes.AND,
  },
  {
    id: FilterOpperatorTypes.OR,
    label: 'Or',
    value: FilterOpperatorTypes.OR,
  },
];
