import { ISelectedListItem } from 'lib/models/general';
import { IElasticField } from 'lib/api/ApiModels/paramBuilders';

export enum IQuryFieldtype {
  STRING = 'string',
  NUMBER = 'number',
}
export interface ISessionsGridField {
  id: string;
  field: string;
  searchField: string;
  queryType?: IQuryFieldtype;
  label: string;
  headerName: string;
  minWidth: number;
  flex: number;
  resizable: boolean;
  hide: boolean;
}

export interface ISessionsGridFieldColumn extends ISessionsGridField {
  hide: boolean;
}

export interface ISessionGridColumns {
  [key: string]: ISessionsGridField;
}

export const SessionGridColumns: ISessionGridColumns = {
  collapseColumn: {
    id: 'aggregatedId',
    field: 'id',
    searchField: '',
    queryType: null,
    label: '',
    headerName: '',
    minWidth: 0,
    flex: 0,
    resizable: false,
    hide: false,
  },
  vendorsColumn: {
    id: 'aggregatedVendors',
    field: 'vendors',
    searchField: '',
    queryType: null,
    label: 'Vendor',
    headerName: 'Vendor',
    minWidth: 200,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  timestamp: {
    id: 'aggregatedTimestamp',
    field: 'timestamp',
    searchField: '@timestamp',
    queryType: IQuryFieldtype.STRING,
    label: 'Time',
    headerName: 'Time',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  startTime: {
    id: 'aggregatedstartTime',
    field: 'startTime',
    searchField: 'start_time',
    queryType: IQuryFieldtype.STRING,
    label: 'Start Time',
    headerName: 'Start Time',
    minWidth: 200,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  endTime: {
    id: 'aggregatedendTime',
    field: 'endTime',
    searchField: 'end_time',
    queryType: IQuryFieldtype.STRING,
    label: 'End Time',
    headerName: 'End Time',
    minWidth: 200,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sessionId: {
    id: 'aggregatedSessionId',
    field: 'sessionId',
    searchField: 'sessionid',
    queryType: IQuryFieldtype.STRING,
    label: 'Session ID',
    headerName: 'Session ID',
    minWidth: 200,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  flowId: {
    id: 'aggregatedFlowId',
    field: 'flowId',
    searchField: 'flowid',
    queryType: IQuryFieldtype.STRING,
    label: 'Flow ID',
    headerName: 'Flow ID',
    minWidth: 200,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  flowDirection: {
    id: 'aggregatedflowDirection',
    field: 'flowDirection',
    searchField: 'flow_direction',
    queryType: IQuryFieldtype.STRING,
    label: 'Flow Direction',
    headerName: 'Flow Direction',
    minWidth: 300,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceIp: {
    id: 'aggregatedSourceIp',
    field: 'sourceIp',
    searchField: 'source_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Source IP',
    headerName: 'Source IP',
    minWidth: 180,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  sourcePort: {
    id: 'aggregatedSourcePort',
    field: 'sourcePort',
    searchField: 'source_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Source Port',
    headerName: 'Source Port',
    minWidth: 180,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  sourceOrgid: {
    id: 'aggregatedsourceOrgid',
    field: 'sourceOrgid',
    searchField: 'source_orgid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Organization ID',
    headerName: 'Source Organization ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceVnetworkExtid: {
    id: 'aggregatedsourceVnetworkExtid',
    field: 'sourceVnetworkExtid',
    searchField: 'source_vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VPC ID',
    headerName: 'Source VPC ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceVnetworkName: {
    id: 'aggregatedsourceVnetworkName',
    field: 'sourceVnetworkName',
    searchField: 'source_vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VPC Name',
    headerName: 'Source VPC Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceSubnetExtid: {
    id: 'aggregatedsourceSubnetExtid',
    field: 'sourceSubnetExtid',
    searchField: 'source_subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Subnet ID',
    headerName: 'Source Subnet ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceVmExtid: {
    id: 'aggregatedsourceVmExtid',
    field: 'sourceVmExtid',
    searchField: 'source_vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VM ID',
    headerName: 'Source VM ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceVmName: {
    id: 'aggregatedsourceVmName',
    field: 'sourceVmName',
    searchField: 'source_vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VM Name',
    headerName: 'Source VM Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceRegion: {
    id: 'aggregatedsourceRegion',
    field: 'sourceRegion',
    searchField: 'source_region',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Region',
    headerName: 'Source Region',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceControllerName: {
    id: 'aggregatedsourceControllerName',
    field: 'sourceControllerName',
    searchField: 'source_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Account Name',
    headerName: 'Source Account Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceControllerId: {
    id: 'aggregatedsourceControllerId',
    field: 'sourceControllerId',
    searchField: 'source_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Account ID',
    headerName: 'Source Account ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceSegmentId: {
    id: 'aggregatedsourceSegmentId',
    field: 'sourceSegmentId',
    searchField: 'source_segment_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Segment ID',
    headerName: 'Source Segment ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  sourceSegmentName: {
    id: 'aggregatedsourceSegmentName',
    field: 'sourceSegmentName',
    searchField: 'source_segment_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Segment Name',
    headerName: 'Source Segment Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  sourceSegmentType: {
    id: 'aggregatedsourceSegmentType',
    field: 'sourceSegmentType',
    searchField: 'source_segment_type',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Segment Type',
    headerName: 'Source Segment Type',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  destIp: {
    id: 'aggregatedDestIp',
    field: 'destIp',
    searchField: 'dest_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination IP',
    headerName: 'Destination IP',
    minWidth: 180,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  destPort: {
    id: 'aggregatedDestPort',
    field: 'destPort',
    searchField: 'dest_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Destination Port',
    headerName: 'Destination Port',
    minWidth: 180,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  destOrgid: {
    id: 'aggregateddestOrgid',
    field: 'destOrgid',
    searchField: 'dest_orgid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Organization ID',
    headerName: 'Destination Organization ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destVnetworkExtid: {
    id: 'aggregateddestVnetworkExtid',
    field: 'destVnetworkExtid',
    searchField: 'dest_vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VPC ID',
    headerName: 'Destination VPC ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destVnetworkName: {
    id: 'aggregateddestVnetworkName',
    field: 'destVnetworkName',
    searchField: 'dest_vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VPC Name',
    headerName: 'Destination VPC Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destSubnetExtid: {
    id: 'aggregateddestSubnetExtid',
    field: 'destSubnetExtid',
    searchField: 'dest_subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Subnet ID',
    headerName: 'Destination Subnet ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destVmExtid: {
    id: 'aggregateddestVmExtid',
    field: 'destVmExtid',
    searchField: 'dest_vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VM ID',
    headerName: 'Destination VM ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destVmName: {
    id: 'aggregateddestVmName',
    field: 'destVmName',
    searchField: 'dest_vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VM Name',
    headerName: 'Destination VM Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destRegion: {
    id: 'aggregateddestRegion',
    field: 'destRegion',
    searchField: 'dest_region',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Region',
    headerName: 'Destination Region',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destControllerName: {
    id: 'aggregateddestControllerName',
    field: 'destControllerName',
    searchField: 'dest_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Account Name',
    headerName: 'Destination Account Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destControllerId: {
    id: 'aggregateddestControllerId',
    field: 'destControllerId',
    searchField: 'dest_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Account ID',
    headerName: 'Destination Account ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destSegmentId: {
    id: 'aggregateddestSegmentId',
    field: 'destSegmentId',
    searchField: 'dest_segment_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Segment ID',
    headerName: 'Destination Segment ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  destSegmentName: {
    id: 'aggregateddestSegmentName',
    field: 'destSegmentName',
    searchField: 'dest_segment_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Segment Name',
    headerName: 'Destination Segment Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  destSegmentType: {
    id: 'aggregateddestSegmentType',
    field: 'destSegmentType',
    searchField: 'dest_segment_type',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Segment Type',
    headerName: 'Destination Segment Type',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  natSourceIp: {
    id: 'aggregatedNatSourceIp',
    field: 'natSourceIp',
    searchField: 'nat_source_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Nat Source IP',
    headerName: 'Nat Source IP',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  natSourcePort: {
    id: 'aggregatedNatSourcePort',
    field: 'natSourcePort',
    searchField: 'nat_source_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Nat Source Port',
    headerName: 'Nat Source Port',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  natDestIp: {
    id: 'aggregatedNatDestIp',
    field: 'natDestIp',
    searchField: 'nat_dest_ip',
    queryType: IQuryFieldtype.STRING,
    label: 'Nat Destination IP',
    headerName: 'Nat Destination IP',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  natDestPort: {
    id: 'aggregatedNatDestPort',
    field: 'natDestPort',
    searchField: 'nat_dest_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Nat Destination Port',
    headerName: 'Nat Destination Port',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  deviceName: {
    id: 'aggregatedDeviceName',
    field: 'deviceName',
    searchField: 'device_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Name',
    headerName: 'Device Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  deviceExtId: {
    id: 'aggregatedDeviceExtId',
    field: 'deviceExtId',
    searchField: 'device_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Device ID',
    headerName: 'Device ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  deviceVendor: {
    id: 'aggregatedDeviceVendor',
    field: 'deviceVendor',
    searchField: 'device_vendor',
    queryType: IQuryFieldtype.STRING,
    label: 'Vendor',
    headerName: 'Vendor',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  deviceNetworkExtid: {
    id: 'aggregateddeviceNetworkExtid',
    field: 'deviceNetworkExtid',
    searchField: 'device_network_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Network ID',
    headerName: 'Device Network ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  deviceControllerId: {
    id: 'aggregateddeviceControllerId',
    field: 'deviceControllerId',
    searchField: 'device_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Account ID',
    headerName: 'Device Account ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  deviceControllerName: {
    id: 'aggregateddeviceControllerName',
    field: 'deviceControllerName',
    searchField: 'device_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Account Name',
    headerName: 'Device Account Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  bytes: {
    id: 'aggregatedDeviceBytes',
    field: 'bytes',
    searchField: 'bytes',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Bytes',
    headerName: 'Bytes',
    minWidth: 160,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  packets: {
    id: 'aggregatedDevicePackets',
    field: 'packets',
    searchField: 'packets',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Packets',
    headerName: 'Packets',
    minWidth: 160,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  action: {
    id: 'aggregatedDeviceAction',
    field: 'action',
    searchField: 'action',
    queryType: IQuryFieldtype.STRING,
    label: 'Action',
    headerName: 'Action',
    minWidth: 160,
    flex: 0.25,
    resizable: false,
    hide: false,
  },
  tcpFlags: {
    id: 'aggregatedDeviceTcpFlags',
    field: 'tcpFlags',
    searchField: 'tcp_flags',
    queryType: IQuryFieldtype.STRING,
    label: 'TCP Flags',
    headerName: 'TCP Flags',
    minWidth: 160,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  trafficType: {
    id: 'aggregatedDeviceTrafficType',
    field: 'trafficType',
    searchField: 'traffic_type',
    queryType: IQuryFieldtype.STRING,
    label: 'Traffic Type',
    headerName: 'Traffic Type',
    minWidth: 160,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  vnetworkExtId: {
    id: 'aggregatedDeviceVnetworkExtId',
    field: 'vnetworkExtId',
    searchField: 'vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'VPC ID',
    headerName: 'VPC ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  vnetworkName: {
    id: 'aggregatedDeviceVnetworkName',
    field: 'vnetworkName',
    searchField: 'vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'VPC Name',
    headerName: 'VPC Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  subnetExtId: {
    id: 'aggregatedDeviceSubnetExtId',
    field: 'subnetExtId',
    searchField: 'subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Subnet ID',
    headerName: 'Subnet ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  subnetName: {
    id: 'aggregatedDeviceSubnetName',
    field: 'subnetName',
    searchField: 'subnet_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Subnet Name',
    headerName: 'Subnet Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  vmExtId: {
    id: 'aggregatedDeviceVmExtId',
    field: 'VmExtId',
    searchField: 'vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'VM ID',
    headerName: 'VM ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  vmName: {
    id: 'aggregatedDeviceVmName',
    field: 'vmName',
    searchField: 'vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'VM Name',
    headerName: 'VM Name',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  region: {
    id: 'aggregatedDeviceRegion',
    field: 'region',
    searchField: 'region',
    queryType: IQuryFieldtype.STRING,
    label: 'Region',
    headerName: 'Region',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  azId: {
    id: 'aggregatedDeviceAzId',
    field: 'azId',
    searchField: 'az_id',
    queryType: IQuryFieldtype.STRING,
    label: 'AZ ID',
    headerName: 'AZ ID',
    minWidth: 240,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  protocol: {
    id: 'aggregatedProtocol',
    field: 'protocol',
    searchField: 'protocol',
    queryType: IQuryFieldtype.STRING,
    label: 'Protocol',
    headerName: 'Protocol',
    minWidth: 140,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
  policyAction: {
    id: 'aggregatedpolicyAction',
    field: 'policyAction',
    searchField: 'policy_action',
    queryType: IQuryFieldtype.STRING,
    label: 'Policy Action',
    headerName: 'Policy Action',
    minWidth: 160,
    flex: 0.25,
    resizable: false,
    hide: true,
  },
};

export const SessionElasticFieldItems: IElasticField[] = [
  {
    resField: SessionGridColumns.timestamp.field,
    searchField: SessionGridColumns.timestamp.searchField,
    queryType: SessionGridColumns.timestamp.queryType,
    label: SessionGridColumns.timestamp.label,
    isField: true,
  },
  {
    resField: SessionGridColumns.sessionId.field,
    searchField: SessionGridColumns.sessionId.searchField,
    queryType: SessionGridColumns.sessionId.queryType,
    label: SessionGridColumns.sessionId.label,
    isField: true,
  },
  {
    resField: SessionGridColumns.flowId.field,
    searchField: SessionGridColumns.flowId.searchField,
    queryType: SessionGridColumns.flowId.queryType,
    label: SessionGridColumns.flowId.label,
    isField: true,
  },
  {
    resField: SessionGridColumns.sourceIp.field,
    searchField: SessionGridColumns.sourceIp.searchField,
    queryType: SessionGridColumns.sourceIp.queryType,
    label: SessionGridColumns.sourceIp.label,
    isField: true,
  },
  {
    resField: SessionGridColumns.sourcePort.field,
    searchField: SessionGridColumns.sourcePort.searchField,
    queryType: SessionGridColumns.sourcePort.queryType,
    label: SessionGridColumns.sourcePort.label,
    isField: true,
  },
  {
    resField: SessionGridColumns.destIp.field,
    searchField: SessionGridColumns.destIp.searchField,
    queryType: SessionGridColumns.destIp.queryType,
    label: SessionGridColumns.destIp.label,
    isField: true,
  },
  {
    resField: SessionGridColumns.destPort.field,
    searchField: SessionGridColumns.destPort.searchField,
    queryType: SessionGridColumns.destPort.queryType,
    label: SessionGridColumns.destPort.label,
    isField: true,
  },
  {
    resField: SessionGridColumns.natSourceIp.field,
    searchField: SessionGridColumns.natSourceIp.searchField,
    queryType: SessionGridColumns.natSourceIp.queryType,
    label: SessionGridColumns.natSourceIp.label,
    isField: true,
  },
  {
    resField: SessionGridColumns.natSourcePort.field,
    searchField: SessionGridColumns.natSourcePort.searchField,
    queryType: SessionGridColumns.natSourcePort.queryType,
    label: SessionGridColumns.natSourcePort.label,
    isField: true,
  },
  {
    resField: SessionGridColumns.natDestIp.field,
    searchField: SessionGridColumns.natDestIp.searchField,
    queryType: SessionGridColumns.natDestIp.queryType,
    label: SessionGridColumns.natDestIp.label,
    isField: true,
  },
  {
    resField: 'natDestPort',
    searchField: 'nat_dest_port',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Nat Destination Port',
    isField: true,
  },
  {
    resField: 'deviceName',
    searchField: 'device_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Name',
    isField: true,
  },
  {
    resField: 'deviceExtId',
    searchField: 'device_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Device ID',
    isField: true,
  },
  {
    resField: 'device',
    searchField: 'device',
    queryType: IQuryFieldtype.STRING,
    label: 'Device',
    isField: true,
  },
  {
    resField: 'deviceVendor',
    searchField: 'device_vendor',
    queryType: IQuryFieldtype.STRING,
    label: 'Vendor',
    isField: true,
  },
  {
    resField: 'bytes',
    searchField: 'bytes',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Bytes',
    isField: true,
  },
  {
    resField: 'packets',
    searchField: 'packets',
    queryType: IQuryFieldtype.NUMBER,
    label: 'Packets',
    isField: true,
  },
  {
    resField: 'action',
    searchField: 'action',
    queryType: IQuryFieldtype.STRING,
    label: 'Action',
    isField: true,
    valueTransform: v => v.toUpperCase(),
  },
  {
    resField: 'tcpFlags',
    searchField: 'tcp_flags',
    queryType: IQuryFieldtype.STRING,
    label: 'TCP Flags',
    isField: true,
  },
  {
    resField: 'trafficType',
    searchField: 'traffic_type',
    queryType: IQuryFieldtype.STRING,
    label: 'Traffic Type',
    isField: true,
  },
  {
    resField: 'vnetworkExtId',
    searchField: 'vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'VPC Id',
    isField: true,
  },
  {
    resField: 'vnetworkName',
    searchField: 'vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'VPC Name',
    isField: true,
  },
  {
    resField: 'subnetExtId',
    searchField: 'subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Subnet Id',
    isField: true,
  },

  {
    resField: 'VmExtId',
    searchField: 'vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'VM Id',
    isField: true,
  },
  {
    resField: 'vmName',
    searchField: 'vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'VM Name',
    isField: true,
  },
  {
    resField: 'region',
    searchField: 'region',
    queryType: IQuryFieldtype.STRING,
    label: 'Region',
    isField: true,
  },
  {
    resField: 'azId',
    searchField: 'az_id',
    queryType: IQuryFieldtype.STRING,
    label: 'AZ Id',
    isField: true,
  },
  {
    resField: 'protocol',
    searchField: 'protocol',
    queryType: IQuryFieldtype.STRING,
    label: 'Protocol',
    isField: true,
  },
  {
    resField: 'policyAction',
    searchField: 'policy_action',
    queryType: IQuryFieldtype.STRING,
    label: 'Policy Action',
    isField: true,
  },
  {
    resField: 'flowDirection',
    searchField: 'flow_direction',
    queryType: IQuryFieldtype.STRING,
    label: 'Flow Direction',
    isField: true,
  },
  {
    resField: 'startTime',
    searchField: 'start_time',
    queryType: IQuryFieldtype.STRING,
    label: 'Start Time',
    isField: true,
  },
  {
    resField: 'endTime',
    searchField: 'end_time',
    queryType: IQuryFieldtype.STRING,
    label: 'End Time',
    isField: true,
  },
  {
    resField: 'deviceNetworkExtid',
    searchField: 'device_network_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Network Ext ID',
    isField: true,
  },
  {
    resField: 'deviceControllerId',
    searchField: 'device_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Controller ID',
    isField: true,
  },
  {
    resField: 'deviceControllerName',
    searchField: 'device_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Device Controller Name',
    isField: true,
  },
  {
    resField: 'sourceOrgid',
    searchField: 'source_orgid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Organization ID',
    isField: true,
  },
  {
    resField: 'sourceVnetworkExtid',
    searchField: 'source_vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Vnetwork Ext ID',
    isField: true,
  },
  {
    resField: 'sourceVnetworkName',
    searchField: 'source_vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Vnetwork Name',
    isField: true,
  },
  {
    resField: 'sourceSubnetExtid',
    searchField: 'source_subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Subnet Ext ID',
    isField: true,
  },
  {
    resField: 'sourceVmExtid',
    searchField: 'source_vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VM Ext ID',
    isField: true,
  },
  {
    resField: 'sourceVmName',
    searchField: 'source_vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source VM Name',
    isField: true,
  },
  {
    resField: 'sourceRegion',
    searchField: 'source_region',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Region',
    isField: true,
  },
  {
    resField: 'sourceControllerName',
    searchField: 'source_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Controller Name',
    isField: true,
  },
  {
    resField: 'sourceControllerId',
    searchField: 'source_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Controller ID',
    isField: true,
  },
  {
    resField: 'sourceSegmentId',
    searchField: 'source_segment_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Segment ID',
    isField: true,
  },
  {
    resField: 'destOrgid',
    searchField: 'dest_orgid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Organization ID',
    isField: true,
  },
  {
    resField: 'destVnetworkExtid',
    searchField: 'dest_vnetwork_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Vnetwork Ext ID',
    isField: true,
  },
  {
    resField: 'destVnetworkName',
    searchField: 'dest_vnetwork_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Vnetwork Name',
    isField: true,
  },
  {
    resField: 'destSubnetExtid',
    searchField: 'dest_subnet_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Subnet Ext ID',
    isField: true,
  },
  {
    resField: 'destVmExtid',
    searchField: 'dest_vm_extid',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VM Ext ID',
    isField: true,
  },
  {
    resField: 'destVmName',
    searchField: 'dest_vm_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination VM Name',
    isField: true,
  },
  {
    resField: 'destRegion',
    searchField: 'dest_region',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Region',
    isField: true,
  },
  {
    resField: 'destControllerName',
    searchField: 'dest_controller_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Controller Name',
    isField: true,
  },
  {
    resField: 'destControllerId',
    searchField: 'dest_controller_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Controller ID',
    isField: true,
  },
  {
    resField: 'destSegmentId',
    searchField: 'dest_segment_id',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Segment ID',
    isField: true,
  },
  {
    resField: 'sourceSegmentName',
    searchField: 'source_segment_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Segment Name',
    isField: true,
  },
  {
    resField: 'sourceSegmentType',
    searchField: 'source_segment_type',
    queryType: IQuryFieldtype.STRING,
    label: 'Source Segment Type',
    isField: true,
  },
  {
    resField: 'destSegmentName',
    searchField: 'dest_segment_name',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Segment Name',
    isField: true,
  },
  {
    resField: 'destSegmentType',
    searchField: 'dest_segment_type',
    queryType: IQuryFieldtype.STRING,
    label: 'Destination Segment Type',
    isField: true,
  },
];

export enum FilterOpperatorTypes {
  AND = 'AND',
  OR = 'OR',
}

export const FilterOpperatorsList: ISelectedListItem<FilterOpperatorTypes>[] = [
  {
    id: FilterOpperatorTypes.AND,
    label: 'And',
    value: FilterOpperatorTypes.AND,
  },
  {
    id: FilterOpperatorTypes.OR,
    label: 'Or',
    value: FilterOpperatorTypes.OR,
  },
];
